### ISSUE TITLE
Initialize periferies out of code

### ISSUE THREAD

**Issue by petrkr** [peterhinch/micropython-micro-gui#1]
Is some way how to initialize SPI/I2C outside of hardware_setup?

This will cause you can not use SPI for other devices (SDCard, card reader etc...) because you can not initialize SPI class more than once.
Add Adjuster widgeAdd Adjuster widget and demos.
t and demos.
2 months ago

lot of internal classes rely on hardware_setup and it's "ssd" object.

I have one solution like I can do "from hardware_setup import spi" to achieve that, but do not know if that is "good" one.

I will rather initialize spi/i2c in my code and then pass it to external libraries

**Comment by peterhinch** [comment]
The intention is that `hardware_setup.py` is a file that you write. This lets you share the bus with other hardware, but you will need to take account of [this mechanism](https://github.com/peterhinch/micropython-micro-gui/blob/main/README.md#26-realtime-applications) to prevent bus contention.
