### ISSUE TITLE
SVG Driver?

### ISSUE THREAD

**Issue by CT-Smyth** [peterhinch/micropython-micro-gui#14]
would it be possible to write an SVG driver so that the output could be written to an SVG file? Perhaps there is a better tool for SVG generation ported to micropython?

**Comment by peterhinch** [comment]
The micro-gui library uses graphics drivers subclassed from `framebuffer.FrameBuffer` and is bitmap based. There is no support for vector graphics.

Your question might be better raised in [the forum](http://[forum](http://forum.micropython.org/index.php).micropython.org/index.php). I believe there is a driver for Hershey fonts but I don't recall anyone working on SVG format - but my memory isn't what it was and I may be wrong here.
