### ISSUE TITLE
Question: Display orientation

### ISSUE THREAD

**Issue by ThinkTransit** [peterhinch/micropython-micro-gui#22]
Hi @peterhinch 

Great library.

Is it possible to rotate the orientation of the screen 180 degrees? I'm using the ili9341 if that makes a difference.

Thanks

**Comment by peterhinch** [comment]
This depends on the particular display driver. With the ILI9341 you're in luck, see [the docs](https://github.com/peterhinch/micropython-nano-gui/blob/master/DRIVERS.md#32-drivers-for-ili9341) - with `usd`, `height` and `width` constructor args you can define any orientation.
