### ISSUE TITLE
Error in docs-- RadioButtons

### ISSUE THREAD

**Issue by bahronheim** [peterhinch/micropython-micro-gui#29]
Sorry if this is a minor issue, but being a novice, it caused me a bit of head scratching until I figured it out...

In the "typical usage" section, the code reads:
 rb = RadioButtons(callback, BLUE) # color of selected button

The constructor for the RadioButtons is: 
def __init__(self, highlight, callback=dolittle, selected=0):

So it expects the highlight color **first**.

So unless I'm mistaken, the parameter positions should be swapped:
 rb = RadioButtons(BLUE, callback) # color of selected button

**Comment by peterhinch** [comment]
Thank you. Now fixed.
