### ISSUE TITLE
Broken links on the docs

### ISSUE THREAD

**Issue by beyonlo** [peterhinch/micropython-micro-gui#35]
Hi Peter!

That two links [TTGO T-Display](http://www.lilygo.cn/prod_view.aspx?TypeId=50044&Id=1126) and [SSD1306 driver](https://github.com/micropython/micropython/blob/master/drivers/display/ssd1306.py) (screenshots below) on the [docs](https://github.com/peterhinch/micropython-micro-gui#readme) are broken:

![image](https://github.com/peterhinch/micropython-micro-gui/assets/630637/1f20fd44-4514-4879-8dd7-14981ed2139b)

![image](https://github.com/peterhinch/micropython-micro-gui/assets/630637/f641e0da-482a-4088-8bdc-8bec4e0e040a)

Thank you!

**Comment by peterhinch** [comment]
Thanks for the report. Now fixed.
